/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleDto } from '../../models/vehicle-dto';
import { VehicleInput } from '../../models/vehicle-input';

export interface VehicleUpdate$Params {
  vehicleId: string;
      body?: VehicleInput
}

export function vehicleUpdate(http: HttpClient, rootUrl: string, params: VehicleUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleDto>> {
  const rb = new RequestBuilder(rootUrl, vehicleUpdate.PATH, 'put');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleDto>;
    })
  );
}

vehicleUpdate.PATH = '/api/v1/vehicles/{vehicleId}';
