/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleDto } from '../../models/vehicle-dto';

export interface VehicleGet$Params {
  vehicleId: string;
}

export function vehicleGet(http: HttpClient, rootUrl: string, params: VehicleGet$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleDto>> {
  const rb = new RequestBuilder(rootUrl, vehicleGet.PATH, 'get');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleDto>;
    })
  );
}

vehicleGet.PATH = '/api/v1/vehicles/{vehicleId}';
