/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecordedEmail } from '../../models/recorded-email';

export interface DevEmails$Plain$Params {
}

export function devEmails$Plain(http: HttpClient, rootUrl: string, params?: DevEmails$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RecordedEmail>>> {
  const rb = new RequestBuilder(rootUrl, devEmails$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RecordedEmail>>;
    })
  );
}

devEmails$Plain.PATH = '/api/v1/dev/emails';
