/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MaintenanceInput } from '../../models/maintenance-input';
import { MaintenanceWriteResult } from '../../models/maintenance-write-result';

export interface MaintenanceUpdate$Params {
  vehicleId: string;
  recordId: string;
      body?: MaintenanceInput
}

export function maintenanceUpdate(http: HttpClient, rootUrl: string, params: MaintenanceUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<MaintenanceWriteResult>> {
  const rb = new RequestBuilder(rootUrl, maintenanceUpdate.PATH, 'put');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
    rb.path('recordId', params.recordId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MaintenanceWriteResult>;
    })
  );
}

maintenanceUpdate.PATH = '/api/v1/vehicles/{vehicleId}/maintenance/{recordId}';
