/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MaintenanceRecordDto } from '../../models/maintenance-record-dto';

export interface MaintenanceList$Params {
  vehicleId: string;
}

export function maintenanceList(http: HttpClient, rootUrl: string, params: MaintenanceList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MaintenanceRecordDto>>> {
  const rb = new RequestBuilder(rootUrl, maintenanceList.PATH, 'get');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MaintenanceRecordDto>>;
    })
  );
}

maintenanceList.PATH = '/api/v1/vehicles/{vehicleId}/maintenance';
