/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MaintenanceDelete$Params {
  vehicleId: string;
  recordId: string;
}

export function maintenanceDelete(http: HttpClient, rootUrl: string, params: MaintenanceDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, maintenanceDelete.PATH, 'delete');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
    rb.path('recordId', params.recordId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

maintenanceDelete.PATH = '/api/v1/vehicles/{vehicleId}/maintenance/{recordId}';
