/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MaintenanceInput {
  costUsd?: number;
  datePerformed?: string;
  description?: string | null;
  mileageAtService?: number;
  notes?: string | null;
  serviceProvider?: string | null;
}
