/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordedEmail {
  link?: string | null;
  sentAt?: string;
  subject?: string | null;
  to?: string | null;
}
