/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidationProblemDetails {
  detail?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;

  [key: string]: ({
[key: string]: Array<string>;
}) | null | any | number | null | string | null | undefined;
}
