/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleInput {
  currentMileage?: number;
  licensePlate?: string | null;
  make?: string | null;
  model?: string | null;
  vin?: string | null;
  year?: number;
}
